### 피쳐 전처리
- 수치형 피쳐 전처리  ==> 스케일링
- 범주형 피쳐 전처리  ==> 인코딩

In [14]:
import numpy as np

In [1]:
from sklearn.preprocessing import LabelEncoder

In [4]:
items = ['티브이', '냉장고', '선풍기', '에어컨']		# array([3, 0, 1, 2])
items = ['티브이', '냉장고', '선풍기', '에어컨']		# array([3, 0, 1, 2])

In [2]:
# 라벨/정수 인코더 인스턴스 생성
lencoder = LabelEncoder()

In [5]:
# 라벨/정수 인코더의 범위 및 맵핑 작업
lencoder.fit(items)

LabelEncoder()

In [6]:
# 라벨/정수값으로 변환
lencoder.transform(items)

array([3, 0, 1, 2])

#### one-hot encoder
- onehotencoder.fit(데이터): 2D 데이터 입력

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [8]:
# 인코더 인스턴스 생성
ohencoder = OneHotEncoder()

In [9]:
# 원핫 인코더 범위 및 맵핑 작업

ohencoder.fit([items])					# items 2D 변환

OneHotEncoder()

In [11]:
# 원핫인코딩 변환
ohencoder.transform([items])

<1x4 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [12]:
oh_items = ohencoder.transform([items])
type(oh_items)

scipy.sparse._csr.csr_matrix

In [13]:
# sparse matrix -> array
oh_items.toarray()
''' 
array([[1., 1., 1., 1.]])
왜냐하면 [ ['냉장고','에어컨'] ] 이렇게 1개의 전체로 선언해서
1,1,1,1 반환

[ ['냉장고'], ['에어컨'] ] 과 같이 선언해야!!
'''

array([[1., 1., 1., 1.]])

In [19]:
# 원핫 인코더 범위 및 맵핑 작업
arr_items = np.array(items).reshape(-1,1)
print(arr_items)
print(arr_items.shape)

ohencoder.fit(arr_items)					# items 2D 변환

[['티브이']
 ['냉장고']
 ['선풍기']
 ['에어컨']]
(4, 1)


OneHotEncoder()

In [17]:
oh_items = ohencoder.transform(arr_items)
type(oh_items)

scipy.sparse._csr.csr_matrix

In [18]:
# sparse matrix -> array
oh_items.toarray()

array([[0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

#### 범주형 피쳐 => 정수형 인코딩

In [20]:
from sklearn.preprocessing import OrdinalEncoder

In [25]:
data = [ ['male', 'C', 'child'], ['male','S','man'], ['female', 'S', 'woman' ] ]

In [26]:
# 정수인코더 인스턴스 생성
odEncoder = OrdinalEncoder()

In [27]:
# 정수 인코딩 범위 및 맵핑 진행
odEncoder.fit(data)				# fit(2D)

OrdinalEncoder()

In [28]:
# 범주 피쳐 ==> 정수 피쳐 변환
odEncoder.transform(data)

array([[1., 0., 0.],
       [1., 1., 1.],
       [0., 1., 2.]])