In [1]:
import torch

#### Tensor생성 [2] torch.rand()

In [5]:
# randn
# 0<= ~ <1 범위 임의의 숫자 1개 추출
torch.manual_seed(1)				# random_seed() 역할

dataTS = torch.rand(3)
print(dataTS, "차원 => ", dataTS.ndim)

tensor([0.7576, 0.2793, 0.4031]) 차원 =>  1


In [6]:
dataTS = torch.rand(2,3)
print(dataTS, "차원 => ", dataTS.ndim)

tensor([[0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695]]) 차원 =>  2


In [7]:
dataTS = torch.rand(2,1,3)				# => 1행 3열 2개
print(dataTS, "차원 => ", dataTS.ndim)

tensor([[[0.4388, 0.6387, 0.5247]],

        [[0.6826, 0.3051, 0.4635]]]) 차원 =>  3


#### Tensor생성 [3] torch.randn()
- n => normalized 준말

In [8]:
dataTS1 = torch.randn(3)		# 1d vector
dataTS2 = torch.randn(2,3)		# 2d matrix
dataTS3 = torch.randn(2,1,3)	# 3d Tensor

print(dataTS1, dataTS2, dataTS3, sep='\n')

tensor([-1.8349, -2.2149,  0.0436])
tensor([[ 1.3240, -0.1005,  0.6443],
        [ 0.5244,  1.0157,  0.2571]])
tensor([[[-0.9013,  0.8138,  0.3871]],

        [[ 0.5417,  0.6646,  0.3248]]])


#### Tensor생성 [3] torch.randint()
- low => 최저값
- high=> 최대값+1
- size=> 차원 크기

In [9]:
torch.randint(1, 5, (3,5))				# 1에서 5미만!	# 3행 5열

tensor([[2, 2, 1, 1, 2],
        [1, 1, 2, 4, 4],
        [3, 2, 1, 3, 4]])

In [10]:
# 2D vector
dataTS1 = torch.randint(1,46, (4,6))
dataTS1

tensor([[40, 24,  4,  4, 17, 33],
        [38, 44,  5, 39, 21, 18],
        [ 8,  4, 21, 40, 45, 26],
        [22, 28, 18,  1, 11, 16]])