### Tensor 이해
- 특정 클래스 선정

#### 타입지정 Tensor 클래스 지정 활용
* 데이터 타입 설정 후 생성
* 사용 목적
	- 데이터 사이즈 설정한 텐서 생성 시
	- 데이터 자료형 변환한 텐서 생성 시

In [2]:
import torch

In [12]:
## 정수형 텐서 생성
data = [0, 2.8, 3.1]

## 1byte 정수형 텐서 생성
# 소수점 아래 버림
# 			=> 데이터 손실!
dataTS1 = torch.CharTensor(data)
print(dataTS1)

## 텐서 함수 Ver.
# 데이터 타입 지정 함수
# 소수점 아래 버림
# 			=> 데이터 손실!
dataTS1_1 = torch.tensor(data, dtype=torch.int8)
print(dataTS1_1)

tensor([0, 2, 3], dtype=torch.int8)
tensor([0, 2, 3], dtype=torch.int8)


C:\Users\KDP-43\AppData\Local\Temp\ipykernel_26952\308677344.py:7: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS1 = torch.CharTensor(data)
C:\Users\KDP-43\AppData\Local\Temp\ipykernel_26952\308677344.py:14: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS1_1 = torch.tensor(data, dtype=torch.int8)


In [13]:
## 2byte 정수형 텐서 생성
# 소수점 아래 버림
# 			=> 데이터 손실!
dataTS1 = torch.ShortTensor(data)
dataTS1_1 = torch.tensor(data, dtype=torch.int16)

print(dataTS1)
print(dataTS1_1)

tensor([0, 2, 3], dtype=torch.int16)
tensor([0, 2, 3], dtype=torch.int16)


C:\Users\KDP-43\AppData\Local\Temp\ipykernel_26952\44012743.py:4: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS1 = torch.ShortTensor(data)
C:\Users\KDP-43\AppData\Local\Temp\ipykernel_26952\44012743.py:5: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS1_1 = torch.tensor(data, dtype=torch.int16)


In [11]:
## 논리형 텐서 생성

dataTS1 = torch.BoolTensor(data)
dataTS1_1 = torch.tensor(data, dtype=torch.bool)

print(dataTS1)
print(dataTS1_1)

tensor([False,  True,  True])
tensor([False,  True,  True])


In [ ]:
##실수형 텐서 생성

dataTS1 = torch.DoubleTensor(data)
dataTS1_1 = torch.tensor(data, dtype=torch.float64)

print(dataTS1)
print(dataTS1_1)

### 텐서 저장/실행 위치 지정
- device 설정으로

In [16]:
## 실행 위치
# => CPU/GPU

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
DEVICE

'cpu'

In [18]:
#----------------------------------
# 함수기능:  텐서 속성 정보 출력 함수
#----------------------------------

def printInfo(obj, obj_name):
    print(f'\n[{obj_name}]')
    print(f'shape: {obj.shape}')
    print(f'ndim: {obj.ndim}차원')
    print(f'dtype: {obj.dtype}')
    print(f'device: {obj.device}')
    print(f'data: \n{obj.data}')

In [21]:
##실수형 텐서 생성

dataTS1 = torch.DoubleTensor(data)
dataTS1_1 = torch.tensor(data, dtype=torch.float64, device=DEVICE)

printInfo(dataTS1, 'tmp1')
printInfo(dataTS1_1, 'tmp1_1')


[tmp1]
shape: torch.Size([3])
ndim: 1차원
dtype: torch.float64
device: cpu
data: 
tensor([0.0000, 2.8000, 3.1000], dtype=torch.float64)

[tmp1_1]
shape: torch.Size([3])
ndim: 1차원
dtype: torch.float64
device: cpu
data: 
tensor([0.0000, 2.8000, 3.1000], dtype=torch.float64)
