### Tensor 이해 & 생성

* Tensor란?
	- pytorch에서 데이터를 저장하는 객체
	- 모델에 입력/출력 데이터 형태
	- 그래프 출력 시에는 numpy로 변환해야!

##### 데이터 타입 (데이터 자료형 범위)
- 기본:	숫자, 글자	=> int, float, char, bool
	* C/c++/C#/Java ==> 스택에 저장
	* python 		==> 힙에 저장 (클래스 기반 객체)
- 확장: 여러 개의 '기본' 데이터 타입이 모여 하나의 데이터 표현
<br></br>
- C => 구조체
- Java 외 OOP => 구조체 + 함수 => 클래스
	* C/c++/C#/Java/python 		==> 힙에 저장 (클래스 기반 객체)

##### Float
- 3.12						=> 정수부=3, 소수점부=0.12 	와 같이 분리해서 컴퓨터가 저장
- 소수점 이하 자릿수
- float => 7/8 				=> 4byte int32
- double => float 소수점 2배 => 8byte double

##### 메모리 관리 25p
* **signed/unsigned**


In [3]:
import torch

# import 패키지 버전 출력 습관!
print(f'torch v.{torch.__version__}')

#----------------------------------
# 함수기능:  텐서 속성 정보 출력 함수
#----------------------------------

def printInfo(obj, obj_name):
    print(f'\n[{obj_name}]')
    print(f'shape: {obj.shape}')
    print(f'ndim: {obj.ndim}차원')
    print(f'dtype: {obj.dtype}')
    print(f'device: {obj.device}')
    print(f'data: \n{obj.data}')
    

torch v.2.4.1


#### 텐서 생성 [1] torch.tensor()

In [6]:
## 스칼라, 데이터 1개
dataTF = torch.tensor(10)
printInfo(dataTF, 'dataTF')

dataTF = torch.tensor(10, dtype=torch.uint8)				# 데이터 저장 메모리 설정
printInfo(dataTF, 'dataTF')


[dataTF]
shape: torch.Size([])
ndim: 0차원
dtype: torch.int64
device: cpu
data: 
10

[dataTF]
shape: torch.Size([])
ndim: 0차원
dtype: torch.uint8
device: cpu
data: 
10


In [7]:
## 행렬 1D, 데이터 1개
dataTF = torch.tensor([10])
printInfo(dataTF, 'dataTF')

dataTF = torch.tensor([], dtype=torch.uint8)				# 데이터 저장 메모리 설정
printInfo(dataTF, 'dataTF')


[dataTF]
shape: torch.Size([1])
ndim: 1차원
dtype: torch.int64
device: cpu
data: 
tensor([10])

[dataTF]
shape: torch.Size([0])
ndim: 1차원
dtype: torch.uint8
device: cpu
data: 
tensor([], dtype=torch.uint8)


In [8]:
## 행렬 2D, 데이터 1개
dataTF = torch.tensor([ [10] ])
printInfo(dataTF, 'dataTF')

dataTF = torch.tensor([ [10,20] ], dtype=torch.uint8)				# 데이터 저장 메모리 설정
printInfo(dataTF, 'dataTF')


[dataTF]
shape: torch.Size([1, 1])
ndim: 2차원
dtype: torch.int64
device: cpu
data: 
tensor([[10]])

[dataTF]
shape: torch.Size([1, 2])
ndim: 2차원
dtype: torch.uint8
device: cpu
data: 
tensor([[10, 20]], dtype=torch.uint8)


In [9]:
## 행렬 4D, 데이터 1개
dataTF = torch.tensor([[[[10]]] ])
printInfo(dataTF, 'dataTF')

dataTF = torch.tensor([[[[10,20]]] ], dtype=torch.uint8)				# 데이터 저장 메모리 설정
printInfo(dataTF, 'dataTF')


[dataTF]
shape: torch.Size([1, 1, 1, 1])
ndim: 4차원
dtype: torch.int64
device: cpu
data: 
tensor([[[[10]]]])

[dataTF]
shape: torch.Size([1, 1, 1, 2])
ndim: 4차원
dtype: torch.uint8
device: cpu
data: 
tensor([[[[10, 20]]]], dtype=torch.uint8)


In [10]:
# ----------------------------------------------------
# 0으로 채운 텐서 생성 : torch.zeros( 행 [, 열 ] )
# ----------------------------------------------------
zten1=torch.zeros(2,5)
zten2=torch.zeros(3)
printInfo(zten1, 'zten1')
printInfo(zten2, 'zten2')


[zten1]
shape: torch.Size([2, 5])
ndim: 2차원
dtype: torch.float32
device: cpu
data: 
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

[zten2]
shape: torch.Size([3])
ndim: 1차원
dtype: torch.float32
device: cpu
data: 
tensor([0., 0., 0.])


In [11]:
# ----------------------------------------------------
# 1로 채운 텐서 생성 : torch.ones( 행 [, 열 ] )
# ----------------------------------------------------
oten1=torch.ones(2,3)
oten2=torch.ones(3)
printInfo(oten1, 'oten1')
printInfo(oten2, 'oten2')


[oten1]
shape: torch.Size([2, 3])
ndim: 2차원
dtype: torch.float32
device: cpu
data: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

[oten2]
shape: torch.Size([3])
ndim: 1차원
dtype: torch.float32
device: cpu
data: 
tensor([1., 1., 1.])


In [12]:
# ------------------------------------------------------------
# 1로 채운 텐서 생성 : torch.full( (행, 열 ), 데이터 )
# -------------------------------------------------------------
ften1=torch.full((3, ), 10)
ften2=torch.full((3,2), 10)
printInfo(ften1, 'ften1')
printInfo(ften2, 'ften2')


[ften1]
shape: torch.Size([3])
ndim: 1차원
dtype: torch.int64
device: cpu
data: 
tensor([10, 10, 10])

[ften2]
shape: torch.Size([3, 2])
ndim: 2차원
dtype: torch.int64
device: cpu
data: 
tensor([[10, 10],
        [10, 10],
        [10, 10]])


In [13]:
# ------------------------------------------------------------
# 1로 채운 텐서 생성 : torch.eye( (행 [, 열 ])
# -------------------------------------------------------------
eten1=torch.eye(3)
eten2=torch.eye(3,5)
printInfo(eten1, 'eten1')
printInfo(eten2, 'eten2')


[eten1]
shape: torch.Size([3, 3])
ndim: 2차원
dtype: torch.float32
device: cpu
data: 
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

[eten2]
shape: torch.Size([3, 5])
ndim: 2차원
dtype: torch.float32
device: cpu
data: 
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])
