### Tensor 변환  
- torch.as_tensor()  
  
    * 동일 타입과 디바이스를 가진 데이터 존재 ==> view 즉, 공유  

    * 다른 타입 또는 다른 디바이스 가진 데이터 존재 ==> copy 즉, 생성  
      
    * view tensor 또는 copy tensor 반환  
    

In [103]:
## 모듈 로딩 
import torch

- Python 객체 ==> Tensor 변환

In [104]:
## List ==> Tensor 
data = list(range(1,10))

In [105]:
## torch.as_tensor()
dataTS = torch.as_tensor(data, dtype=torch.int8)

In [106]:
dataTS, dataTS.shape, dataTS.ndim, dataTS.dtype

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8),
 torch.Size([9]),
 1,
 torch.int8)

In [107]:
data[0] = 100

In [108]:
data, dataTS

([100, 2, 3, 4, 5, 6, 7, 8, 9],
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8))

- Numpy ndarray 객체 ==> Tensor 변환 

In [109]:
import numpy as np

In [110]:
arr1 = np.array([1,2,3])
arr1 

array([1, 2, 3])

In [111]:
arrTS = torch.as_tensor(arr1)
arrTS, arr1.dtype, arr1.ndim

(tensor([1, 2, 3], dtype=torch.int32), dtype('int32'), 1)

In [112]:
arr1[0] = 77

In [113]:
arrTS[0] = 99

In [114]:
# copy가 올지 view가 올지 모르는 상황 -> 이 경우는 
arr1, arrTS

(array([99,  2,  3]), tensor([99,  2,  3], dtype=torch.int32))

- Numpy ndarray ==> Tensor 변환 : from_numpy()

In [115]:
arr1 = np.array([5,7,9], dtype= np.float32)
#         데이터 메모리 주소     데이터 개수      데이터 1개 크기 
arr1,         arr1.data,        arr1.size ,      arr1.itemsize

(array([5., 7., 9.], dtype=float32), <memory at 0x00000000086C11C0>, 3, 4)

In [116]:
print(arr1)
print(f'데이터 저장 메모리  : {arr1.data}')
print(f'원소/요소 개수      : {arr1.size}')
print(f'원소/요소 1개 크기  : {arr1.itemsize}')
print(f'탄입               : {arr1.dtype}')
print(f'방향               : {arr1.strides}')

[5. 7. 9.]
데이터 저장 메모리  : <memory at 0x00000000086C1400>
원소/요소 개수      : 3
원소/요소 1개 크기  : 4
탄입               : float32
방향               : (4,)


In [117]:
# 2차원인 경우 
arr1 = np.array([[5,7,9],[1,2,3]], dtype= np.float16)
print(arr1)
print(f'데이터 저장 메모리  : {arr1.data}')
print(f'원소/요소 개수      : {arr1.size}')
print(f'원소/요소 1개 크기  : {arr1.itemsize}')
print(f'탄입               : {arr1.dtype}')
print(f'방향               : {arr1.strides}')
# 12 --> 0번행에서 1번행으로 가기까지 걸리는 칸수 

[[5. 7. 9.]
 [1. 2. 3.]]
데이터 저장 메모리  : <memory at 0x000000000ED9CA00>
원소/요소 개수      : 6
원소/요소 1개 크기  : 2
탄입               : float16
방향               : (6, 2)


In [118]:
arrTS = torch.from_numpy(arr1) 
arrTS

tensor([[5., 7., 9.],
        [1., 2., 3.]], dtype=torch.float16)

#### Tensor 이해 - 형변환

In [119]:
#### 모듈로딩
import torch

- 방법 [1] type(torch.XXXX)

In [120]:
# tensor 생성
dataTS1 = torch.tensor([1,3,5])
dataTS1, dataTS1.dtype

(tensor([1, 3, 5]), torch.int64)

In [121]:
# int64 -> float 
dataTS11 = dataTS1.type(torch.float32)
dataTS11, dataTS11.dtype

(tensor([1., 3., 5.]), torch.float32)

- 방법 [2] 타입명()

In [122]:
# int64 -> float
dataTS11 = dataTS11.float()
dataTS11, dataTS11.dtype

(tensor([1., 3., 5.]), torch.float32)

In [124]:
# int64 --> bool
dataTS1.bool()

tensor([True, True, True])

- 방법 [3] to(dtype=OOO,device=OOO)

In [125]:
# int64 --> bool
dataTS1.to(dtype=torch.int8)

tensor([1, 3, 5], dtype=torch.int8)

In [128]:
dataTS1.to(dtype=torch.int8, 
           device='cuda' if torch.cuda.is_available() else 'cpu')
#          'cuda' 없으면 'cpu'해줘
# cuda가 없어서 error 뜸

tensor([1, 3, 5], dtype=torch.int8)

In [129]:
dataTS1[0], dataTS1[-1]

tensor(1)

In [131]:
dataTS1[:2], dataTS1[-2:]

(tensor([1, 3]), tensor([3, 5]))