### Tensor
- 모양
- 형태
- shape 변경
- View Tensor

In [1]:
import torch
import numpy as np

In [6]:
dataTS = torch.arange(1, 21)
print(dataTS, dataTS.ndim, dataTS.stride(), sep='\n')

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])
1
(1,)


In [11]:
print(dataTS.storage())

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]


In [9]:
# 1D => 2D 형태/모양/shape 변경
dataTS2 = dataTS.reshape( (-1,5) )
print(dataTS2, dataTS2.ndim, dataTS2.stride(), sep='\n')

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])
2
(5, 1)


In [10]:
print(dataTS2.storage())

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]


C:\Users\KDP-43\AppData\Local\Temp\ipykernel_23696\104493862.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(dataTS2.storage())


In [13]:
dataTS2[0][0] = 77

In [17]:
dataTS, dataTS2
## View?? Copy??

(tensor([77,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20]),
 tensor([[77,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]))

In [21]:
dataTS22 = dataTS2.reshape( (-1,2))
print(dataTS22, dataTS22.ndim, dataTS22.stride(), sep='\n')
print("is_contiguous: ", dataTS2.is_contiguous())

tensor([[77,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]])
2
(2, 1)
is_contiguous:  True


In [22]:
dataTS22.T

tensor([[77,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]])

In [23]:
dataTS22.T.shape

torch.Size([2, 10])

In [27]:
dataTS_23 = dataTS22.T
print(dataTS_23)
dataTS_23.is_contiguous()

tensor([[77,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]])


False

In [25]:
dataTS_23.storage()

 77
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]

##### 불연속 => 연속 전환
- tensor_obj.contiguous()

In [28]:
dataTS_23.contiguous().storage()

 77
 3
 5
 7
 9
 11
 13
 15
 17
 19
 2
 4
 6
 8
 10
 12
 14
 16
 18
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]

- 위에 결과와 storage 원소 순서가 다름