### Tensor- 형변환

In [1]:
import torch

In [2]:
# tensor 생성
dataTS1 = torch.tensor( [1,3,5] )
dataTS1, dataTS1.dtype 

(tensor([1, 3, 5]), torch.int64)

In [4]:
# int64 -> float
dataTS1_1 = dataTS1.type(torch.float32)
dataTS1_1, dataTS1_1.dtype

(tensor([1., 3., 5.]), torch.float32)

#### 방법 [2] 타입명()

In [5]:
dataTS1 = torch.tensor( [1,3,5] )

dataTS1_1 = dataTS1_1.float()
dataTS1_1, dataTS1_1.dtype

(tensor([1., 3., 5.]), torch.float32)

In [6]:
# int64 -> bool
dataTS1.bool()

tensor([True, True, True])

#### 방법 [3] to(dtype=OOO, device=OOO)

In [7]:
# int64 -> bool
dataTS1.to(dtype=torch.int8)

tensor([1, 3, 5], dtype=torch.int8)

In [8]:
dataTS1.to(dtype=torch.int8, 
           device='cuda' if torch.cuda.is_available() else 'cpu')

tensor([1, 3, 5], dtype=torch.int8)