### Tensor 변환
- torch.as_tensor()
	* 동일 타입 & 디바이스 존재 	==>) View w.m) 데이터 공유		=> 하나라도 변경 시, 모두 변경
	* 다른 타입 or 다른 디바이스를 가진 데이터	==> copy() 생성! 
	* view tensor or copy tensor 반환

In [18]:
import torch

#### Python 객체 변환

In [19]:
# List => Tensor
data = list( range(1,10))

dataTS = torch.as_tensor(data, dtype=torch.int8)
dataTS, dataTS.shape, dataTS.ndim, dataTS.dtype

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8),
 torch.Size([9]),
 1,
 torch.int8)

In [20]:
data[0] = 100
data,dataTS

([100, 2, 3, 4, 5, 6, 7, 8, 9],
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8))

#### Numpy ndarray => Tensor

In [21]:
import numpy as np

In [22]:
arr1 = np.array( [1,2,3] )
arr1, arr1.dtype, arr1.ndim

(array([1, 2, 3]), dtype('int32'), 1)

In [23]:
arrTS = torch.as_tensor(arr1, dtype=torch.float32)
arrTS

tensor([1., 2., 3.])

In [24]:
arr1[0] = 77

In [25]:
arr1, arrTS

(array([77,  2,  3]), tensor([1., 2., 3.]))

In [ ]:
arrTS[0] = 99

- 저장된 위치가 같다면 'sharing'되어 'View'로써
- 저장된 위치가 다르다면 'copy'되어 '복사본'으로써

- Numpy ndarray => Tensor
	* from_numpy()

In [29]:
arr1 = np.array( [5,7,9], dtype=np.float32)
print(arr1)
print(f'데이터 저장 메모리:	{arr1.data}')
print(f'원소/요소 개수: {arr1.size}')
print(f'원소/요소 1개 크기: {arr1.itemsize}')
print(f'타입: {arr1.dtype}')
print(f'방향: {arr1.strides}')

[5. 7. 9.]
데이터 저장 메모리:	<memory at 0x0000023519CF3E80>
원소/요소 개수: 3
원소/요소 1개 크기: 4
타입: float32
방향: (4,)


In [33]:
arr1 = np.array( [[5,7,9],[1,2,3]], dtype=np.float32)
print(arr1)
print(f'데이터 저장 메모리:	{arr1.data}')
print(f'원소/요소 개수: {arr1.size}')
print(f'원소/요소 1개 크기: {arr1.itemsize}')
print(f'타입: {arr1.dtype}')
print(f'방향: {arr1.strides}')					# 방향: (12, 4) 1개 메모리 4칸 소요 => 4*3=12

[[5. 7. 9.]
 [1. 2. 3.]]
데이터 저장 메모리:	<memory at 0x0000023519CB0930>
원소/요소 개수: 6
원소/요소 1개 크기: 4
타입: float32
방향: (12, 4)


In [34]:
arr1 = np.array( [[5,7,9],[1,2,3]], dtype=np.float16)
print(arr1)
print(f'데이터 저장 메모리:	{arr1.data}')
print(f'원소/요소 개수: {arr1.size}')
print(f'원소/요소 1개 크기: {arr1.itemsize}')	# 원소/요소 1개 크기: 2 	=> 메모리상 2칸 차지
print(f'타입: {arr1.dtype}')
print(f'방향: {arr1.strides}')					# 방향: (12, 4) 1개 메모리 4칸 소요 => 4*3=12

[[5. 7. 9.]
 [1. 2. 3.]]
데이터 저장 메모리:	<memory at 0x0000023519CB0930>
원소/요소 개수: 6
원소/요소 1개 크기: 2
타입: float16
방향: (6, 2)


In [36]:
arrTS = torch.from_numpy(arr1)
arrTS

tensor([[5., 7., 9.],
        [1., 2., 3.]], dtype=torch.float16)